server:
  port: 8090

spring:
  application:
    name: api-gateway
  main:
    web-application-type : reactive

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        security: DEBUG